### PR TITLE
RFC 005 - Visualize Flow

### PR DESCRIPTION
**Pull request by craigjbass**
Visualize all work in progress

### CODE REVIEW

**Comment by kjdchapman** [comment]
+1 for this being a great thing for us to do.
Less sure on whether to include it in, say, delivery standards docs.

Visualising work and holding retrospectives are the only two things I've seen provide value for **every** team. I want to do this, and I would recommend other people do this.

I have a little hesitation about this being a MUST rather than a SHOULD. I prefer recommendations to rules in the case of autonomous, trusted teams.

**Comment by craigjbass** [comment]
@kjdchapman what do you propose?

**Comment by kjdchapman** [comment]
@craigjbass As an alternative to including it in delivery standards? I could see it in [Development Practices](https://github.com/madetech/handbook/blob/master/team-norms/development_practices.md), for example.

Devil's advocate: my worry is that these docs become larger and don't get read, whereas Delivery Standards have to be acted upon.

**Comment by craigjbass** [comment]
@kjdchapman I think the outcome of an RFC could be to update these other handbooks? Not sure.

**Comment by kjdchapman** [comment]
@craigjbass it's all new to me!

From the README: 
> The outcomes of these discussions can be either an Action Plan, or a new Standard that Made Tech should follow.

I assume this means updating the handbook in some way would be the outcome for something like this.

**Comment by RyanMacG** [comment]
If this was true for "all" projects it should become part of the healthcheck, then it could be opted out off with good reason. So yeah "should" not "must"

**Comment by SebAshton** [comment]
Although I believe all teams are _probably_ (?) doing this, we should potentially add an action point to add this to our delivery guidelines?

Also, a point of admin - can you add a description to this PR 😁

**Pull request merged**
