### PR TITLE
RFC #2 Adopt TDD as a Team Norm

### PR DESCRIPTION
**Pull request by craigjbass**
**Formally adopt TDD as an expectation of all Engineers at Made Tech**

### CODE REVIEW

**Comment by lukemorton** [comment]
Looks good so far.

Are we saying TDD is has to be unit tests? If we are we probably want to adapt the RFC to mention specific types of code that must be TDD'd with unit tests. I see a few exceptions as they're usually covered by browser based acceptance tests:

- Controllers
- Views
- Rails configuration and locale changes
- CSS changes

**Comment by chrisblackburn** [comment]
@craigjbass whagwan?

**Comment by craigjbass** [comment]
@chrisblackburn team has had 6 working days to review. Loads of people on hols. Will give 1 more week

**Comment by chrisblackburn** [comment]
@lukemorton I wonder how this fits with the Engineer competencies and Core Engineer expectations?

**Comment by craigjbass** [comment]
@chrisblackburn I think this is attempting to bit a lot more granular about 

a) When we're talking about TDD, what that specifically means
b) Situations in which we agree we can&should break the "rule"

**Comment by chrisblackburn** [comment]
Yep, I think they largely complement

**Pull request merged**
