### PR TITLE
Discussion on "Who we work with"

### PR DESCRIPTION
**Pull request by kjdchapman**
# Discussion: Who we work with

## Problem

I have concerns about working with certain companies, and want to see how other people at Made feel about it.

If we don't have this conversation, we might end up working in a way that doesn't reflect our shared values, because we all assumed it was just us with those concerns.

The intent of this RFC is to gather that understanding, **not** to jump ahead and propose any restrictions on who we work with.

## Proposal

A discussion, against this PR - are there companies that you wouldn't want to work with? How strongly do you feel about that?

Please bear in mind this could be a sensitive topic. I don't want to see anyone trying to shame other people because of personal ethics.

No-one should feel obliged to participate, but if you have a neutral opinion on this ("I'm happy for us to work with anyone"), it would be good to hear from you. Having thoughts from only people who feel strongly might give a false picture of how we feel as a group.

### CODE REVIEW

**Comment by kjdchapman** [comment]
_(And now my personal feelings on the matter. I didn't want to muddy the original PR with this - this is an example of what I'd be interested to hear from people.)_

I wanted to start this discussion after I noticed that Lockheed Martin is one of our potential clients. That's a company I'd be worried about working with.

The options, to my mind, are:
1) We refuse to work with a company
2) We agree to work with them, but only on certain projects
3) We agree to work with them, but try to avoid having people who objected work on the relevant teams
4) We agree to work with them with no restrictions

My personal preference would be 1), but I can see 3) as a workable solution.

I understand there's a commercial impact from any sort of restrictions. I would want us to try to consider the trade-offs for any potential partnership, and could see (as an extreme example) taking on work that was personally objectionable in order to keep Made going.

I understand not everyone feels the same as me. I would be uncomfortable pushing client restrictions if many people at Made aren't interested in them.

**Comment by RyanMacG** [comment]
We've discussed this in the past (in a comradro) with regards to certain Gov departments and I certainly wouldn't be personally comfortable working with Lockheed Martin (or any other similar company).

Based on a pragmatic approach of; They are already a target customer so some sort of value/interest must exist at a certain level I think that option 3 is the workable solution. Obviously if everyone were to object that would cause an interesting problem.

**Comment by kjdchapman** [comment]
@RyanMacG this isn't specifically about LM, it was just a useful example. I'm more interested in how we handle for future clients, and to get a feel for what % of us care.

I'd be interested to hear what the conclusions were from any previous discussions.

Just a note for future commenters: this is a **public repo**, so be respectful to potential future clients. You could also argue for a discussion in another forum, if that's making people feel unsafe (thanks to @danielburnley for the sensible note).

**Comment by RyanMacG** [comment]
I understood that I meant in the sense we don't really know what potential customs are in the pipeline until it is mentioned/brought to our attention it feels like 3  would be the only solution that could work unless the directors held a straw poll everytime they wanted to target a new company which feels unachievable and like it could limit growth.

Ideally I'd want 1 but I think it can't work.

**Comment by camillavk** [comment]
I also agree that option 1 would be ideal but it probably wouldn't work. I do feel it is important to me that, at the very least, I would be able to state that I do not want to work on a specific project because of my feelings about the company and that this would be taken into account (option 3). 

With this in mind I do think that if such a situation did arise currently, if I explained my reasoning behind not wanting to work on a project this would already be taken into account (but having not had to do this yet, I can't be sure of this, obviously :) ).

Also option 2 feels like a bit of a "shallow" option, and I definitely don't like option 4.

**Comment by kjdchapman** [comment]
Some discussion offline/on slack has suggested it might be good to run a Comradro on this.

I'm going to leave this open a little longer, as I'm still interested to hear people's opinions.

**Comment by DelphineGattaz** [comment]
Even though I am less directly impacted, I also feel this is an important topic. 
I believe it is very hard to give your best for a project you feel is not in line with your values, or you don't want to be a part of. 

That being said we all have our own lines we don't wish to cross. 
And there might be certain types of company (arms dealers could be an example?) regarding which we can (probably?) all align on, and say no we are not working for them (= option 1). There will also be a grey area where some of us would be ok and some of us wouldn't. For which option 3 seems the most viable. 

Great idea to have a Comrado on this topic.

**Comment by StevenLeighton21** [comment]
Suggest closing this now that we've had action points added to the handbook? Unless there's more actions off the back of this to come out.

**Comment by kjdchapman** [comment]
For reference, the Handbook addition is [here](https://github.com/madetech/handbook/pull/150), and it's now merged (which is great!).

This PR was opened without me (having joined recently) knowing the Directors' opinions on this - they already had a policy of the above, the PR just puts it in writing. Seems good!

There's still an outstanding question of who we _as Made Tech_ want to work for.  From our discussions so far, flat refusing to work with people seems like a rare case. Maybe we'll continue that discussion at a later stage.

I've got a (slight) outstanding worry that new starters won't find the relevant information as the handbook continues to grow, but it's on me to work out how/if I can make it clearer.

Closing this.

**Pull request closed without merging**
