### PR TITLE
RFC 011 - introduce editorconfig for projects

### PR DESCRIPTION
**Pull request by cybojenix**
Proposal to make use of [editorconfig](https://editorconfig.org/)

### CODE REVIEW

**Comment by StevenLeighton21** [comment]
Concept is excellent, though I feel adding an editor config per project is more overhead than having an RFC that provides a base config (2 spaces instead of tab, etc) and just requesting everyone use that + their own config.

**Comment by cybojenix** [comment]
I get where you're coming from.
While it may take less time to have everyone configure their environments to a set config, the result is something less explicit within the code.
I'm not suggesting we proactively go back and add an editorconfig to all projects, more that they be added retroactively.

Clear advantages over configuring an editor manually:
- It's explicitly written in code, so no dispute of meaning
- It will work for external contributors (either community or clients)
- It will work with the github editor
- It gives a clear base and example of how to apply styles for a specific project

This also ties into an over-arching plan relating to standardising tools that **will** actually need project level configurations.

**Comment by SebAshton** [comment]
I've always advocated the use of EditorConfig, even added the one to [Spree/Solidus](https://github.com/solidusio/solidus/blob/master/.editorconfig) many moons ago.

However, it's never been enforced strictly till now because not everyone's editors supported the all the features that editorconfig supports, and in some cases didn't have an extension at all. I expect this may have/probably has changed since the last review.

**Comment by StevenLeighton21** [comment]
I'm sold on the concept - perhaps and RFC requesting everyone uses a config compatible editor?

**Comment by cybojenix** [comment]
Think a less-harsh move might be:
> You **SHOULD** use an editor that supports `.editorconfig`, either natively or via a plugin
> If you use an editor that does not support `.editorconfig`, then you **MUST** configure the editor in such a way that mirrors the project's editorconfig rules

**Comment by StevenLeighton21** [comment]
Seems fine to me

**Comment by cybojenix** [comment]
@SebAshton @StevenLeighton21, I've added the proposed rule from above about configuring your editor if `.editorconfig` is unavailable to you

**Pull request merged**
