### PR TITLE
RFC 007 - Suggestion outlining code review keywords

### PR DESCRIPTION
**Pull request by StevenLeighton21**
Outline code review keywords to be used to easily provide clarity, confidence and context to review comments.

### CODE REVIEW

**Comment by craigjbass** [comment]
:heart: this

**Comment by kjdchapman** [comment]
Love the sentiment behind this. Not sure about the implementation.

Think it's good to try and get to a common understanding of what a code review contains (discussion and questions as well as requested changes). 

Not sure if going for a MUST/SHOULD model is correct in this case. I feel like my place is to recommend changes and discuss if the other person agrees, rather than _insisting_ something changes. It's hard to get tone correct in written reviews. 

I'd rather we had a series of recommendations on language use, to help us get to a shared position without mandating words.

**Comment by StevenLeighton21** [comment]
@kjdchapman Super valid point and I agree to an extent, I like the SHOULD/MUST paradigm personally for the following reasons:
Sometimes, your comment is pointing out a fundamental logic flaw etc that really MUST be changed before you can approve this request. Insisting on a change or at least a discussion is OK by me, personally.
Sometimes, you may be pointing out something like 'this gateway SHOULD be two gateways because it currently does two things that are related but sort of separate, but that's reasonably involved and we're pushed for time.' In this second case, you're pointing out what you'd recommend as advice/learning for the future as it probably isn't going to get changed, even if that is an objectively good change to make. I like this personally because as a reviewer, if I know this is the case I may not leave the comment at all, but this way having the comment and discussion in the PR is great for reference if you're ever digging through past commits trying to figure something out.

**Comment by kjdchapman** [comment]
@StevenLeighton21 agree with the distinction between levels of advice, just would avoid the keywords being _mandated_ rather than _recommended_.

Looks like people like it as it is though, so happy to give it a go.

**Comment by craigjbass** [comment]
@kjdchapman in a situation where you can see harm would come from a PR being merged, would you still take the _recommended_ stance? Maybe there something between mandated and recommended.

**Comment by kjdchapman** [comment]
@craigjbass I feel like I already have a tool to say "wait, this is dangerous, don't merge!" - a failed review.

I'm not arguing for **not allowing** language like "You must not merge this because of X". I'd still write that in some cases.

I'm arguing we should allow people to use **whatever language they like** to get the message across, with recommended phrases for certain purposes.

Compare:

> In keeping with the [RFC2119-style](https://www.ietf.org/rfc/rfc2119.txt), reviewers MUST use one and only one of the following keywords as part of the review comment...

And:

> If you're commenting on a critical mistake, try using a phrase like 'This must be changed, as X will result for Y reasons.".
> If you're commenting to try and improve code quality, try using a phrase like 'This class feels like it's responsible for multiple things. Have you considered dividing them?'
> (etc)

I prefer the latter style - recommendations over rules - when we're trying to encourage certain behaviours amongst trusted, skilled professionals with common purpose.

**Comment by StevenLeighton21** [comment]
@kjdchapman We already allow for whatever language, the aim of the change is to clarify that language into some handy keywords that provide context at a glance. I'd have assumed that use of _must_ would be rare, realistically. _Suggest_ is a vehicle for making recommendations in a way that removes any confusion about recommendation vs requirement, allowing comments to be more concise, and allowing comments that are purely recommendations to not slow down the review process.

**Pull request merged**
